version: '3.3'

services:

  mysql:
    image:  mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: productdb
    ports:
      - "3306:3306"
    expose:
      - "3306"

#    volumes:
#      - ./mysql-product-data:/var/lib/mysql
#
#
#volumes:
#  mysql-product-data: