server:
  port: 8081

spring:
  graphql:
    graphiql:
      enabled: true
  application:
    name: product-graph-api
  datasource:
    product:
      url: jdbc:mysql://localhost:3306/productdb
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


logging:
  level:
    org:
      hibernate.SQL: DEBUG
